#!/bin/bash 

set -e
set -o pipefail

LOG_DIR=/var/vcap/sys/log/pmm-server
LOG_FILE=$LOG_DIR/pmm-prestart.combined.log
PROC_NAME=pmm-server
RUN_DIR=/var/vcap/sys/run/$PROC_NAME

mkdir -p $LOG_DIR
mkdir -p $RUN_DIR

apt-get update

apt-get install -y --no-install-recommends \
    linux-image-extra-$(uname -r) \
    linux-image-extra-virtual

apt-get install -y --no-install-recommends \
    apt-transport-https \
    ca-certificates \
    curl \
    software-properties-common

curl -fsSL https://apt.dockerproject.org/gpg | sudo apt-key add -

add-apt-repository \
       "deb https://apt.dockerproject.org/repo/ \
       ubuntu-$(lsb_release -cs) \
       main"

apt-get update

apt-get -y install docker-engine
